### PR TITLE
Replace AlphaBanner with PhaseBanner from gcui

### PR DESCRIPTION
**Pull request by sleepycat**
This cleans up and simplifies the component with further optimizations coming soon.
Usage is simply this:

```javascript
<PhaseBanner beta>
  This is a new service we are constantly improving.
</PhaseBanner>
```

### CODE REVIEW

**Comment by pcraig3** [comment]
At the minute, it's still a bit rough.

### desktop view 


| before | after |
|--------|-------|
|  screen shot 2018-05-16 at 4 25 33 pm   |  screen shot 2018-05-16 at 4 26 10 pm   |
|    aligned with the canadian flag    |   No longer aligned with the flag, or the other stuff on the page     |


### mobile view

| before | after |
|--------|-------|
|   screen shot 2018-05-16 at 4 26 35 pm   |   screen shot 2018-05-16 at 4 27 14 pm  |
|   nice amount of space between badge and text   |   text is too close to the badge, so it's a bit squished. (this is because there's some bottom padding on the badge component on smaller screens.) |

**Comment by sleepycat** [comment]
Thanks! New version soon.

**Comment by sleepycat** [comment]
OK, take another look. If you see anything else let me know.

**Comment by pcraig3** [comment]
## desktop
Still moves the text off the baseline of the Alpha banner

banner-1

## mobile
Text moves up and to the right a bit. Ideally, we want the text to be flush with the edge of the alpha button.

banner-2

**Comment by pcraig3** [comment]
Also the colour of the Alpha button changes from what it is [on the Products page of the CDS website](https://digital.canada.ca/products/). 

The one on the website is `#F90277` or `rgb(249,2,119)`.
The new one is `rgb(232,2,110)`. 

Not super opinionated about that, but is there a reason to change it?

**Comment by sleepycat** [comment]
The colour is deliberate. Talking with Max, he ran AXE on it and it pointed out that there isn't enough contrast between the text and the background on the badge, so he shifted it a little and I went with it.
I'll take a look at the other alignment stuff.

**Comment by pcraig3** [comment]
I've just updated this with some overriding CSS code. Check it out, @sleepycat. Merge if you think it looks good.

**Pull request merged**
