### PR TITLE
Give focus to selected day box

### PR DESCRIPTION
**Pull request by timarney**
When coming back from the review page this will give focus to the selected day box to make it eaier to remove days before moving back to the calendar.

### CODE REVIEW

**Comment by pcraig3** [comment]
Couple things:
- Not sure if we do want an outline -- looks worse with it, imo
- Not sure if we want to update the hash (#calendar-header) to somewhere else (#removeDateMessage) for example

Can ask @emanelfy on Monday

**Comment by timarney** [comment]
> * Not sure if we want to update the hash (#calendar-header) to somewhere else (#removeDateMessage) for example

Updated the return link to use /calendar#selected-day-box.  The other hash didn't work well for the mobile view.

**Comment by emanelfy** [comment]
**Outstanding change on the calendar page:**
When a selection is made on the calendar, the active colour should be green (to match the same colour as the button).

Additionally, on the above point -- no outline required :)

**Comment by timarney** [comment]
Making the cal colour updates here https://github.com/cds-snc/ircc-rescheduler/pull/479

**Pull request merged**
